export default [
  {
    isDouble: false,
    productType: "vehicle",
    imageSrc: "is6.png",
    title: "ИС-6",
    flag: "ussr",
    vehicleType: "heavytank",
    level: "IX",
    price: 47.99,
  },
  {
    isDouble: false,
    productType: "vehicle",
    imageSrc: "lowe.png",
    title: "Lowe",
    flag: "germany",
    vehicleType: "heavytank",
    level: "VIII",
    price: 42.99,
  },
  {
    productType: "extension",
    isDouble: false,
    imageSrc: "extension.png",
    title: "EXTENSION PACK",
    price: 28.99,
  },
  {
    productType: "premium",
    isDouble: false,
    imageSrc: "premium3.png",
    title: "WOT PREMIUM ACCOUNT: 3 DAYS",
    price: 2.99,
  },
  {
    productType: "vehicle",
    isDouble: true,
    imageSrc: "m56.png",
    title: "M56 SCORPION",
    flag: "usa",
    vehicleType: "at-spg",
    level: "VII",
    price: 24.99,
  },
  {
    productType: "vehicle",
    isDouble: false,
    imageSrc: "fv4202.png",
    title: "FV4202",
    flag: "uk",
    vehicleType: "mediumtank",
    level: "VIII",
    price: 40.99,
  },
  {
    productType: "vehicle",
    isDouble: false,
    imageSrc: "revalorise.png",
    title: "M4A1 REVALORISE",
    flag: "france",
    vehicleType: "mediumtank",
    level: "VIII",
    price: 35.99,
  },
  {
    productType: "reserves",
    isDouble: false,
    imageSrc: "reserves.png",
    title: "10 PERSONAL RESERVES: +15% XP LIMITED EDITION",
    price: 29.99,
  },
  {
    productType: "gold",
    isDouble: false,
    imageSrc: "gold.png",
    title: "GOLD 25.000",
    price: 99.99,
  },
  {
    productType: "vehicle",
    isDouble: true,
    imageSrc: "t92.png",
    title: "T92",
    flag: "usa",
    vehicleType: "multirole",
    level: "VIII",
    price: 36.99,
  },
];
